version: "3.8"
services:
  app:
    image: ghcr.io/realize-engineering/ideal-computing-machine:main
    depends_on:
      - db
      - cache
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    user: nextjs
    env_file: .env
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@db:5432/olli
      - REDIS_URL=redis://cache:6379
      - OPENAI_BASE_URL=https://openai-proxy.olli.ai/v1

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=olli
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
