name: Upload Objects to S3 Bucket

on:
    push:
        branches: ["main"]

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"
            - name: Install dependencies
              run: pip install -r ./deploy/scripts/update_s3/requirements.txt
            - name: Upload objects to bucket
              env:
                  S3_USER_ACCESS_ID: ${{secrets.S3_USER_ACCESS_ID}}
                  S3_USER_SECRET_KEY: ${{secrets.S3_USER_SECRET_KEY}}
                  PIPEBIRD_CONFIG_BUCKET_NAME: ${{secrets.PIPEBIRD_CONFIG_BUCKET_NAME}}
              run: python deploy/scripts/update_s3
